name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore FluentSqlBuilder.sln
      working-directory: src
    
    - name: Build
      run: dotnet build FluentSqlBuilder.sln --no-restore
      working-directory: src
    
    - name: Test
      run: dotnet test FluentSqlBuilder.sln --no-build --verbosity normal
      working-directory: src

    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.3.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/FluentSqlBuilder.Core/FluentSqlBuilder.Core.csproj
        # NuGet package id to check against version changes, defaults to project name
        #PACKAGE_NAME: # optional
        # Filepath containing version info, relative to root of repository
        #VERSION_FILE_PATH: # optional
        # Regex pattern to extract version info in a capturing group
        #VERSION_REGEX: # optional, default is <Version>(.*)<\/Version>
        # Static version, useful for external providers like Nerdbank.GitVersioning
        #VERSION_STATIC: # optional
        # Flag to enable / disable git tagging
        TAG_COMMIT: false # optional, default is true
        # Format of the git tag, `[*]` gets replaced with version
        #TAG_FORMAT: # optional, default is v*
        # API key for the NuGet feed
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }} # optional



