name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore FluentSqlBuilder.sln
      working-directory: src
    
    - name: Build
      run: dotnet build FluentSqlBuilder.sln --no-restore
      working-directory: src
    
    - name: Test
      run: dotnet test FluentSqlBuilder.sln --no-build --verbosity normal
      working-directory: src

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output .
    
    - name: Push
      run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}




