name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore FluentSqlBuilder.sln
      working-directory: src
    - name: Build
      run: dotnet build FluentSqlBuilder.sln --no-restore
      working-directory: src
    - name: Test
      run: dotnet test FluentSqlBuilder.sln --no-build --verbosity normal
      working-directory: src
